language: php
php:
  - "5.4"
  - "5.5"

notifications:
  email:
    - dev@zucchi.co.uk

branches:
  only:
    - master

services:
  - mongodb
  - memcached

before_script:
   - composer self-update
   - composer install --dev --prefer-source
   - mysql -e 'create database test_zucchimodel;'
   - pwd
   - ls -al

script: "`pwd`/vendor/bin/codecept run -c `pwd`/codeception.travis.yml"
