<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiModel\Annotation\Relationship'          => __DIR__ . '//src/ZucchiModel/Annotation/Relationship.php',
    'ZucchiModel\Annotation\Field'                 => __DIR__ . '//src/ZucchiModel/Annotation/Field.php',
    'ZucchiModel\Annotation\ModelMetadataListener' => __DIR__ . '//src/ZucchiModel/Annotation/ModelMetadataListener.php',
    'ZucchiModel\ModelManager'                     => __DIR__ . '//src/ZucchiModel/ModelManager.php',
    'ZucchiModel\Model\ModelTrait'                 => __DIR__ . '//src/ZucchiModel/Model/ModelTrait.php',
    'ZucchiModel\Model\IdentityTrait'              => __DIR__ . '//src/ZucchiModel/Model/IdentityTrait.php',
    'ZucchiModel\Metadata\Fields'                  => __DIR__ . '//src/ZucchiModel/MetaData/Fields.php',
    'ZucchiModel\Metadata\Model'                   => __DIR__ . '//src/ZucchiModel/MetaData/Model.php',
    'ZucchiModel\Module'                           => __DIR__ . '//Module.php',
);